### ISSUE TITLE
Motivation?

### ISSUE THREAD

**Issue by listener17** [mgraczyk/tf_visqol#1]
Interesting work! What's the motivation for this work? Any plans to extend to ViSQOL v3?

**Comment by mgraczyk** [comment]
I wrote this around the time I was at Google working on audio. More as a learning experience than for any practical use. We used ViSQOL to estimate perceptual quality for various projects. I haven't worked on audio much since then. 

I suspect that there are better libraries out there for high quality differentiable audio loss functions. For very large models, you probably don't need or shouldn't use a metric like this. Instead just go with L2 on the mel spectrogram or similar.

**Comment by listener17** [comment]
OK, thanks. So you wanted a "differentiable audio loss function".
